---
- name: Install docker
  gather_facts: No
  hosts: testservers

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest




    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user maverick to docker group
      user:
        name: maverick
        groups: docker
        append: yes
      become: yes

    - name: Execute a command using the shell module
      become: yes
      become_user: root
      shell: docker pull nginx

    - name: Execute a command using the shell module
      become: yes
      become_user: root
      shell: docker run --name interviewdemo -p 80:80 -d nginx

    - name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
      copy:
        src: /etc/ansible/playbooks/index.html
        dest: /root/index.html
        follow: yes

    - name: Execute a command using the shell module
      become: yes
      become_user: root
      shell: docker cp /root/index.html interviewdemo:/usr/share/nginx/html/index.html

    - name: Execute a command using the shell module
      become: yes
      become_user: root
      shell: docker cp /root/index.html interviewdemo:/usr/share/nginx/html/index.html

    - name: Execute a command using the shell module
      become: yes
      become_user: root
      shell: docker container exec interviewdemo nginx -s reload
